name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repo
              uses: actions/checkout@v2.3.1
            - name: Use Node.js
              uses: actions/setup-node@v2.1.4
              with:
                  node-version: '14.x'
            - run: yarn install
            - run: yarn build
            - name: Archive production artifacts
              uses: actions/upload-artifact@v2.2.2
              with:
                  name: dist
                  path: dist
